[build]
  command = "npm install --force && VITE_DISABLE_NATIVE=true npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
  VITE_DISABLE_NATIVE = "true"
  NPM_FLAGS = "--legacy-peer-deps --force"